"use client"
import React from 'react';
import ReactFlow, { MiniMap, Controls, Background, useNodesState, useEdgesState, BackgroundVariant } from 'reactflow';
import 'reactflow/dist/style.css';



const initialNodes = [
    { id: '1', type: 'input', data: { label: 'Brief History of Computer Systems' }, position: { x: 250, y: 0 } },
    { id: '2', data: { label: 'Definition of Computer' }, position: { x: 100, y: 100 } },
    { id: '3', data: { label: 'Importance of Computer History' }, position: { x: 400, y: 100 } },
    { id: '4', data: { label: 'Programmable electronic device' }, position: { x: 50, y: 200 } },
    { id: '5', data: { label: 'Performs arithmetic and logical operations' }, position: { x: 150, y: 200 } },
    { id: '6', data: { label: 'Uses a set of instructions' }, position: { x: 250, y: 200 } },
    { id: '7', data: { label: 'Understanding technological evolution' }, position: { x: 350, y: 200 } },
    { id: '8', data: { label: 'Impact on current technology' }, position: { x: 450, y: 200 } },
    { id: '9', data: { label: 'Early Computing Devices' }, position: { x: 250, y: 300 } },
    { id: '10', data: { label: 'Abacus' }, position: { x: 100, y: 400 } },
    { id: '11', data: { label: 'One of the earliest counting devices' }, position: { x: 50, y: 500 } },
    { id: '12', data: { label: 'Uses beads or stones on rods or wires' }, position: { x: 150, y: 500 } },
    { id: '13', data: { label: 'Used for centuries in various cultures' }, position: { x: 250, y: 500 } },
    { id: '14', data: { label: 'Used for arithmetic calculations' }, position: { x: 350, y: 500 } },
    { id: '15', data: { label: "Napier's Bone" }, position: { x: 450, y: 400 } },
    { id: '16', data: { label: 'Developed by John Napier' }, position: { x: 400, y: 500 } },
    { id: '17', data: { label: 'Manually operated calculating device' }, position: { x: 500, y: 500 } },
    { id: '18', data: { label: 'Used for multiplication and division' }, position: { x: 600, y: 500 } },
    { id: '19', data: { label: 'Used 9 separate strips (bones) marked with numerals' }, position: { x: 700, y: 500 } },
    { id: '20', data: { label: 'First machine to calculate using decimal point system' }, position: { x: 800, y: 500 } },
    { id: '21', data: { label: 'Pascaline' }, position: { x: 100, y: 600 } },
    { id: '22', data: { label: 'Invented in 1642 by Blaise Pascal' }, position: { x: 50, y: 700 } },
    { id: '23', data: { label: 'First mechanical and automated calculator' }, position: { x: 150, y: 700 } },
    { id: '24', data: { label: 'Consisted of a wooden box with gears and wheels' }, position: { x: 250, y: 700 } },
    { id: '25', data: { label: 'Stepped Reckoner (Leibniz wheel)' }, position: { x: 450, y: 600 } },
    { id: '26', data: { label: 'Created in 1673 by Wilhelm Leibniz' }, position: { x: 400, y: 700 } },
    { id: '27', data: { label: 'Improved version of Pascal\'s invention' }, position: { x: 500, y: 700 } },
    { id: '28', data: { label: 'Used grooved wheels for calculations' }, position: { x: 600, y: 700 } },
    { id: '29', data: { label: 'Difference Engine' }, position: { x: 100, y: 800 } },
    { id: '30', data: { label: 'Created by Charles Babbage in early 1820s' }, position: { x: 50, y: 900 } },
    { id: '31', data: { label: 'Steam-powered calculating machine' }, position: { x: 150, y: 900 } },
    { id: '32', data: { label: 'Used to solve numerical problems' }, position: { x: 250, y: 900 } },
    { id: '33', data: { label: 'Analytical Engine' }, position: { x: 450, y: 800 } },
    { id: '34', data: { label: 'Created by Charles Babbage in 1830' }, position: { x: 400, y: 900 } },
    { id: '35', data: { label: 'Took input from punch cards' }, position: { x: 500, y: 900 } },
    { id: '36', data: { label: 'Capable of solving any mathematical problem and storing data' }, position: { x: 600, y: 900 } },
    { id: '37', data: { label: 'Tabulating Machine' }, position: { x: 100, y: 1000 } },
    { id: '38', data: { label: 'Invented by Herman Hollerith in 1890' }, position: { x: 50, y: 1100 } },
    { id: '39', data: { label: 'Punch card-based mechanical calculator' }, position: { x: 150, y: 1100 } },
    { id: '40', data: { label: 'Could compute statistics and record data' }, position: { x: 250, y: 1100 } },
    { id: '41', data: { label: 'Led to the formation of IBM in 1924' }, position: { x: 350, y: 1100 } },
    { id: '42', data: { label: 'Differential Analyzer' }, position: { x: 450, y: 1000 } },
    { id: '43', data: { label: 'Introduced by Vannevar Bush in 1930' }, position: { x: 400, y: 1100 } },
    { id: '44', data: { label: 'First electrical computer' }, position: { x: 500, y: 1100 } },
    { id: '45', data: { label: 'Used vacuum tubes as switches' }, position: { x: 600, y: 1100 } },
    { id: '46', data: { label: 'Could perform 25 calculations per minute' }, position: { x: 700, y: 1100 } },
    { id: '47', data: { label: 'Mark 1' }, position: { x: 100, y: 1200 } },
    { id: '48', data: { label: 'Invented by Howard Aiken in 1944' }, position: { x: 50, y: 1300 } },
    { id: '49', data: { label: 'Digital computer' }, position: { x: 150, y: 1300 } },
    { id: '50', data: { label: 'Could add three 8-digit numbers in one second' }, position: { x: 250, y: 1300 } },
    { id: '51', data: { label: '50 feet long, 8 feet high, weighed 5 tons' }, position: { x: 350, y: 1300 } },
    { id: '52', data: { label: 'Used 3,000 electric switches' }, position: { x: 450, y: 1300 } },
    { id: '53', data: { label: 'Computer Generations' }, position: { x: 250, y: 1400 } },
    { id: '54', data: { label: 'First Generation (1940-1956)' }, position: { x: 100, y: 1500 } },
    { id: '55', data: { label: 'Used vacuum tubes' }, position: { x: 50, y: 1600 } },
    { id: '56', data: { label: 'Very expensive' }, position: { x: 150, y: 1600 } },
    { id: '57', data: { label: 'Consisted of magnetic drums' }, position: { x: 250, y: 1600 } },
    { id: '58', data: { label: 'ENIAC' }, position: { x: 350, y: 1600 } },
    { id: '59', data: { label: 'Second Generation (1956-1963)' }, position: { x: 450, y: 1500 } },
    { id: '60', data: { label: 'Used transistors' }, position: { x: 400, y: 1600 } },
    { id: '61', data: { label: 'Cheaper' }, position: { x: 500, y: 1600 } },
    { id: '62', data: { label: 'Used magnetic cores' }, position: { x: 600, y: 1600 } },
    { id: '63', data: { label: 'IBM 1401' }, position: { x: 700, y: 1600 } },
    { id: '64', data: { label: 'Third Generation (1964-1971)' }, position: { x: 100, y: 1700 } },
    { id: '65', data: { label: 'Used integrated circuits' }, position: { x: 50, y: 1800 } },
    { id: '66', data: { label: 'Cheaper' }, position: { x: 150, y: 1800 } },
    { id: '67', data: { label: 'Used semiconductors' }, position: { x: 250, y: 1800 } },
    { id: '68', data: { label: 'IBM System/360' }, position: { x: 350, y: 1800 } },
    { id: '69', data: { label: 'Fourth Generation (1971-Present)' }, position: { x: 450, y: 1700 } },
    { id: '70', data: { label: 'Used microprocessors' }, position: { x: 400, y: 1800 } },
    { id: '71', data: { label: 'Cheaper and faster' }, position: { x: 500, y: 1800 } },
    { id: '72', data: { label: 'Uses VLSI and ULSI' }, position: { x: 600, y: 1800 } },
    { id: '73', data: { label: 'First microprocessor was Intel 4004' }, position: { x: 700, y: 1800 } },
    { id: '74', data: { label: 'Fifth Generation (Present and Beyond)' }, position: { x: 100, y: 1900 } },
    { id: '75', data: { label: 'Uses artificial intelligence (AI)' }, position: { x: 50, y: 2000 } },
    { id: '76', data: { label: 'Natural language processing' }, position: { x: 150, y: 2000 } },
    { id: '77', data: { label: 'Quantum computation' }, position: { x: 250, y: 2000 } },
    { id: '78', data: { label: 'Nanotechnology' }, position: { x: 350, y: 2000 } },
    { id: '79', data: { label: 'IBM Watson' }, position: { x: 450, y: 2000 } },
];

const initialEdges = [
    { id: 'e1-2', source: '1', target: '2', animated: true },
    { id: 'e1-3', source: '1', target: '3', animated: true },
    { id: 'e2-4', source: '2', target: '4', animated: true },
    { id: 'e2-5', source: '2', target: '5', animated: true },
    { id: 'e2-6', source: '2', target: '6', animated: true },
    { id: 'e3-7', source: '3', target: '7', animated: true },
    { id: 'e3-8', source: '3', target: '8', animated: true },
    { id: 'e1-9', source: '1', target: '9', animated: true },
    { id: 'e9-10', source: '9', target: '10', animated: true },
    { id: 'e10-11', source: '10', target: '11', animated: true },
    { id: 'e10-12', source: '10', target: '12', animated: true },
    { id: 'e10-13', source: '10', target: '13', animated: true },
    { id: 'e10-14', source: '10', target: '14', animated: true },
    { id: 'e9-15', source: '9', target: '15', animated: true },
    { id: 'e15-16', source: '15', target: '16', animated: true },
    { id: 'e15-17', source: '15', target: '17', animated: true },
    { id: 'e15-18', source: '15', target: '18', animated: true },
    { id: 'e15-19', source: '15', target: '19', animated: true },
    { id: 'e15-20', source: '15', target: '20', animated: true },
    { id: 'e9-21', source: '9', target: '21', animated: true },
    { id: 'e21-22', source: '21', target: '22', animated: true },
    { id: 'e21-23', source: '21', target: '23', animated: true },
    { id: 'e21-24', source: '21', target: '24', animated: true },
    { id: 'e9-25', source: '9', target: '25', animated: true },
    { id: 'e25-26', source: '25', target: '26', animated: true },
    { id: 'e25-27', source: '25', target: '27', animated: true },
    { id: 'e25-28', source: '25', target: '28', animated: true },
    { id: 'e9-29', source: '9', target: '29', animated: true },
    { id: 'e29-30', source: '29', target: '30', animated: true },
    { id: 'e29-31', source: '29', target: '31', animated: true },
    { id: 'e29-32', source: '29', target: '32', animated: true },
    { id: 'e9-33', source: '9', target: '33', animated: true },
    { id: 'e33-34', source: '33', target: '34', animated: true },
    { id: 'e33-35', source: '33', target: '35', animated: true },
    { id: 'e33-36', source: '33', target: '36', animated: true },
    { id: 'e9-37', source: '9', target: '37', animated: true },
    { id: 'e37-38', source: '37', target: '38', animated: true },
    { id: 'e37-39', source: '37', target: '39', animated: true },
    { id: 'e37-40', source: '37', target: '40', animated: true },
    { id: 'e37-41', source: '37', target: '41', animated: true },
    { id: 'e9-42', source: '9', target: '42', animated: true },
    { id: 'e42-43', source: '42', target: '43', animated: true },
    { id: 'e42-44', source: '42', target: '44', animated: true },
    { id: 'e42-45', source: '42', target: '45', animated: true },
    { id: 'e42-46', source: '42', target: '46', animated: true },
    { id: 'e9-47', source: '9', target: '47', animated: true },
    { id: 'e47-48', source: '47', target: '48', animated: true },
    { id: 'e47-49', source: '47', target: '49', animated: true },
    { id: 'e47-50', source: '47', target: '50', animated: true },
    { id: 'e47-51', source: '47', target: '51', animated: true },
    { id: 'e1-52', source: '1', target: '52', animated: true },
    { id: 'e52-53', source: '52', target: '53', animated: true },
    { id: 'e53-54', source: '53', target: '54', animated: true },
    { id: 'e53-55', source: '53', target: '55', animated: true },
    { id: 'e53-56', source: '53', target: '56', animated: true },
    { id: 'e53-57', source: '53', target: '57', animated: true },
    { id: 'e53-58', source: '53', target: '58', animated: true },
    { id: 'e52-59', source: '52', target: '59', animated: true },
    { id: 'e59-60', source: '59', target: '60', animated: true },
    { id: 'e59-61', source: '59', target: '61', animated: true },
    { id: 'e59-62', source: '59', target: '62', animated: true },
    { id: 'e59-63', source: '59', target: '63', animated: true },
    { id: 'e52-64', source: '52', target: '64', animated: true },
    { id: 'e64-65', source: '64', target: '65', animated: true },
    { id: 'e64-66', source: '64', target: '66', animated: true },
    { id: 'e64-67', source: '64', target: '67', animated: true },
    { id: 'e64-68', source: '64', target: '68', animated: true },
    { id: 'e52-69', source: '52', target: '69', animated: true },
    { id: 'e69-70', source: '69', target: '70', animated: true },
    { id: 'e69-71', source: '69', target: '71', animated: true },
    { id: 'e69-72', source: '69', target: '72', animated: true },
    { id: 'e69-73', source: '69', target: '73', animated: true },
    { id: 'e52-74', source: '52', target: '74', animated: true },
    { id: 'e74-75', source: '74', target: '75', animated: true },
    { id: 'e74-76', source: '74', target: '76', animated: true },
    { id: 'e74-77', source: '74', target: '77', animated: true },
    { id: 'e74-78', source: '74', target: '78', animated: true },
    { id: 'e74-79', source: '74', target: '79', animated: true },
];

const Page = () => {
    const [nodes, setNodes, onNodesChange] = useNodesState(initialNodes);
    const [edges, setEdges, onEdgesChange] = useEdgesState(initialEdges);

    return (
        <div style={{ width: '100%', height: '600px' }}>
            <ReactFlow
                nodes={nodes}
                edges={edges}
                onNodesChange={onNodesChange}
                onEdgesChange={onEdgesChange}
                fitView
            >
                <Controls />
                <MiniMap />
                <Background variant={BackgroundVariant.Dots} gap={12} size={1} />
            </ReactFlow>
        </div>
    );
}

export default Page;
